# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
      AppBundle\Entity\User: plaintext

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_db:
          entity:
            class: AppBundle:User
            property: name

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        #dev:
        #    pattern: ^/(_(profiler|wdt)|css|images|js)/
        #    security: false

        main:
            #anonymous: ~
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            pattern: .*
            http_basic:
              provider: user_db
            logout:
              path: /logout
              target: /
              invalidate_session: true


            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~

    access_control:
      - { path: ^/task/(.*?)/close, roles: ROLE_SUPERVISOR }
