AppBundle\Entity\TaskStatusHistory:
    type: entity
    table: task_status_history
    id:
        historyId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: history_id
            generator:
                strategy: IDENTITY
    fields:
        ts:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
    lifecycleCallbacks: {  }

    oneToOne:
      taskId:
        targetEntity: AppBundle\Entity\Task
        joinColumn:
          name: task_id
          referencedColumnName: task_id
      statusId:
        targetEntity: AppBundle\Entity\TaskStatus
        joinColumn:
          name: status_id
          referencedColumnName: status_id
      userId:
        targetEntity: AppBundle\Entity\User
        joinColumn:
          name: user_id
          referencedColumnName: user_id
