AppBundle\Entity\User:
    type: entity
    table: user
    id:
        userId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: user_id
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
    lifecycleCallbacks: {  }

    oneToOne:
      roleId:
        targetEntity: AppBundle\Entity\UserRole
        joinColumn:
          name: role_id
          referencedColumnName: role_id
